# Generated by Django 3.0.6 on 2020-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
