# Generated by Django 3.0.6 on 2020-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_placedorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
    ]
