# Generated by Django 3.0.6 on 2020-05-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='placedorders',
            name='orderno',
            field=models.IntegerField(default=1),
        ),
    ]
