# Generated by Django 3.0.6 on 2020-05-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200511_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderno',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orderno',
        ),
        migrations.RemoveField(
            model_name='placedorders',
            name='orderno',
        ),
    ]
