# Generated by Django 3.0.6 on 2020-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_dinnerplatters_pasta_salads_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='salads',
            name='name',
            field=models.TextField(max_length=64),
        ),
    ]
