# Generated by Django 3.0.6 on 2020-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200511_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='salads',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
