# Generated by Django 3.0.6 on 2020-05-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200512_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorders',
            name='no',
        ),
    ]
