# Generated by Django 3.0.6 on 2020-05-12 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_placedorders_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorders',
            name='no',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
