# Generated by Django 3.0.6 on 2020-05-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_placedorders_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorders',
            name='no',
        ),
    ]
