# Generated by Django 3.0.6 on 2020-05-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_placedorders_ordertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorders',
            name='ordertime',
        ),
    ]
