# Generated by Django 3.0.6 on 2020-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200512_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersplaced',
            name='ordertime',
            field=models.DateTimeField(),
        ),
    ]
