# Generated by Django 3.0.6 on 2020-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200512_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersplaced',
            name='ordertime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
