# Generated by Django 3.0.6 on 2020-05-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200512_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdersPlaced',
        ),
    ]
